package cn.com.sunjiesh.thirdpartdemo.model;

import java.util.Date;

public class WechatUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.id
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.city
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.country
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.create_time
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.create_user
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.head_img_url
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String headImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.language
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.nickname
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.open_id
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.province
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.remark
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.sex
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.subscribe
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String subscribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.subscribe_time
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private Date subscribeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.union_id
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String unionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.update_time
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.update_user
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.id
     *
     * @return the value of wechat_user.id
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.id
     *
     * @param id the value for wechat_user.id
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.city
     *
     * @return the value of wechat_user.city
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.city
     *
     * @param city the value for wechat_user.city
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.country
     *
     * @return the value of wechat_user.country
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.country
     *
     * @param country the value for wechat_user.country
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.create_time
     *
     * @return the value of wechat_user.create_time
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.create_time
     *
     * @param createTime the value for wechat_user.create_time
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.create_user
     *
     * @return the value of wechat_user.create_user
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.create_user
     *
     * @param createUser the value for wechat_user.create_user
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.head_img_url
     *
     * @return the value of wechat_user.head_img_url
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getHeadImgUrl() {
        return headImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.head_img_url
     *
     * @param headImgUrl the value for wechat_user.head_img_url
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setHeadImgUrl(String headImgUrl) {
        this.headImgUrl = headImgUrl == null ? null : headImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.language
     *
     * @return the value of wechat_user.language
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.language
     *
     * @param language the value for wechat_user.language
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.nickname
     *
     * @return the value of wechat_user.nickname
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.nickname
     *
     * @param nickname the value for wechat_user.nickname
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.open_id
     *
     * @return the value of wechat_user.open_id
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.open_id
     *
     * @param openId the value for wechat_user.open_id
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.province
     *
     * @return the value of wechat_user.province
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.province
     *
     * @param province the value for wechat_user.province
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.remark
     *
     * @return the value of wechat_user.remark
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.remark
     *
     * @param remark the value for wechat_user.remark
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.sex
     *
     * @return the value of wechat_user.sex
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.sex
     *
     * @param sex the value for wechat_user.sex
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.subscribe
     *
     * @return the value of wechat_user.subscribe
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getSubscribe() {
        return subscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.subscribe
     *
     * @param subscribe the value for wechat_user.subscribe
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setSubscribe(String subscribe) {
        this.subscribe = subscribe == null ? null : subscribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.subscribe_time
     *
     * @return the value of wechat_user.subscribe_time
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public Date getSubscribeTime() {
        return subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.subscribe_time
     *
     * @param subscribeTime the value for wechat_user.subscribe_time
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setSubscribeTime(Date subscribeTime) {
        this.subscribeTime = subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.union_id
     *
     * @return the value of wechat_user.union_id
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.union_id
     *
     * @param unionId the value for wechat_user.union_id
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId == null ? null : unionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.update_time
     *
     * @return the value of wechat_user.update_time
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.update_time
     *
     * @param updateTime the value for wechat_user.update_time
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.update_user
     *
     * @return the value of wechat_user.update_user
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.update_user
     *
     * @param updateUser the value for wechat_user.update_user
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}