package cn.com.sunjiesh.thirdpartdemo.model;

public class AppUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.id
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.account_expired
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private Boolean accountExpired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.account_locked
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private Boolean accountLocked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.address
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.city
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.country
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.postal_code
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String postalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.province
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.credentials_expired
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private Boolean credentialsExpired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.email
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.account_enabled
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private Boolean accountEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.first_name
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.last_name
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.password
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.password_hint
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String passwordHint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.phone_number
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.username
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.version
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.website
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    private String website;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.id
     *
     * @return the value of app_user.id
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.id
     *
     * @param id the value for app_user.id
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.account_expired
     *
     * @return the value of app_user.account_expired
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public Boolean getAccountExpired() {
        return accountExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.account_expired
     *
     * @param accountExpired the value for app_user.account_expired
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setAccountExpired(Boolean accountExpired) {
        this.accountExpired = accountExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.account_locked
     *
     * @return the value of app_user.account_locked
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public Boolean getAccountLocked() {
        return accountLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.account_locked
     *
     * @param accountLocked the value for app_user.account_locked
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setAccountLocked(Boolean accountLocked) {
        this.accountLocked = accountLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.address
     *
     * @return the value of app_user.address
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.address
     *
     * @param address the value for app_user.address
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.city
     *
     * @return the value of app_user.city
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.city
     *
     * @param city the value for app_user.city
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.country
     *
     * @return the value of app_user.country
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.country
     *
     * @param country the value for app_user.country
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.postal_code
     *
     * @return the value of app_user.postal_code
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.postal_code
     *
     * @param postalCode the value for app_user.postal_code
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode == null ? null : postalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.province
     *
     * @return the value of app_user.province
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.province
     *
     * @param province the value for app_user.province
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.credentials_expired
     *
     * @return the value of app_user.credentials_expired
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public Boolean getCredentialsExpired() {
        return credentialsExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.credentials_expired
     *
     * @param credentialsExpired the value for app_user.credentials_expired
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setCredentialsExpired(Boolean credentialsExpired) {
        this.credentialsExpired = credentialsExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.email
     *
     * @return the value of app_user.email
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.email
     *
     * @param email the value for app_user.email
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.account_enabled
     *
     * @return the value of app_user.account_enabled
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public Boolean getAccountEnabled() {
        return accountEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.account_enabled
     *
     * @param accountEnabled the value for app_user.account_enabled
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setAccountEnabled(Boolean accountEnabled) {
        this.accountEnabled = accountEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.first_name
     *
     * @return the value of app_user.first_name
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.first_name
     *
     * @param firstName the value for app_user.first_name
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.last_name
     *
     * @return the value of app_user.last_name
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.last_name
     *
     * @param lastName the value for app_user.last_name
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.password
     *
     * @return the value of app_user.password
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.password
     *
     * @param password the value for app_user.password
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.password_hint
     *
     * @return the value of app_user.password_hint
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getPasswordHint() {
        return passwordHint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.password_hint
     *
     * @param passwordHint the value for app_user.password_hint
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setPasswordHint(String passwordHint) {
        this.passwordHint = passwordHint == null ? null : passwordHint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.phone_number
     *
     * @return the value of app_user.phone_number
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.phone_number
     *
     * @param phoneNumber the value for app_user.phone_number
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.username
     *
     * @return the value of app_user.username
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.username
     *
     * @param username the value for app_user.username
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.version
     *
     * @return the value of app_user.version
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.version
     *
     * @param version the value for app_user.version
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.website
     *
     * @return the value of app_user.website
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.website
     *
     * @param website the value for app_user.website
     *
     * @mbggenerated Fri Oct 23 21:12:59 CST 2015
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }
}