package cn.com.sunjiesh.thirdpartdemo.dao;

import cn.com.sunjiesh.thirdpartdemo.model.WechatUser;
import cn.com.sunjiesh.thirdpartdemo.model.WechatUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WechatUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbggenerated Fri Oct 23 21:13:00 CST 2015
     */
    int countByExample(WechatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbggenerated Fri Oct 23 21:13:00 CST 2015
     */
    int deleteByExample(WechatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbggenerated Fri Oct 23 21:13:00 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbggenerated Fri Oct 23 21:13:00 CST 2015
     */
    int insert(WechatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbggenerated Fri Oct 23 21:13:00 CST 2015
     */
    int insertSelective(WechatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbggenerated Fri Oct 23 21:13:00 CST 2015
     */
    List<WechatUser> selectByExample(WechatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbggenerated Fri Oct 23 21:13:00 CST 2015
     */
    WechatUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbggenerated Fri Oct 23 21:13:00 CST 2015
     */
    int updateByExampleSelective(@Param("record") WechatUser record, @Param("example") WechatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbggenerated Fri Oct 23 21:13:00 CST 2015
     */
    int updateByExample(@Param("record") WechatUser record, @Param("example") WechatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbggenerated Fri Oct 23 21:13:00 CST 2015
     */
    int updateByPrimaryKeySelective(WechatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbggenerated Fri Oct 23 21:13:00 CST 2015
     */
    int updateByPrimaryKey(WechatUser record);
}