#Server settings
server:
    port:8080

# DATASOURCE
jdbc:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://localhost:3306/thirdpartydemo?useUnicode=true&charaterEncoding=utf-8
    databaseName: test
    serverName: 127.0.0.1
    username: root
    password: password
    cachePrepStmts: true
    prepStmtsSize: 250
    prepStmtsCacheSqlLimit: 2048
    userServerPrepStmts: true

# SPRING PROFILES
spring:       
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true

# MyBatis
mybatis:
    typeAliasesPackage: cn.com.sunjiesh.thirdpartdemo.model
    mapperLocations: classpath:/cn/com/sunjiesh/thirdpartdemo/mapper/*.xml
    configLocation: classpath:/mybatis-config.xml

# LOGGING
logging:
    level:
       com.ibatis:DEBUG